import { useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'ja' | 'fr' | 'pt';

export const LANGUAGE_NAMES: Record<Language, string> = {
    en: 'English (EN)',
    es: 'Español (ES)',
    ja: '日本語 (JA)',
    fr: 'Français (FR)',
    pt: 'Português (PT)'
};

// Humorous, elegant, clear localization values
export const LOCALIZATION_DICTS: Record<Language, Record<string, string>> = {
    en: {
        app_title: 'SEN Workshop',
        app_sub: 'Visual faces for SEN Light Novels (Reader Chamber & Living Codex)',
        created_by: 'Created for SEN Light Novels',
        face_family_title: 'Face Family',
        face_family_sub: 'Coordinated Visual Themes across Reader Chamber & Living Codex',
        settings_title: 'Settings',
        library_title: 'Library',
        how_to_use: 'How to Use',
        exit_error: 'Start Over / Exit',
        gen_failed: 'Generation Failed',
        pres_select: 'Select a face target...',
        btn_send: 'Generate Face',
        vibe_dna: 'Style DNA Customizer',
        saved_to_lib: 'Visual Face saved to Library!',
        no_components: 'No saved visual faces yet.',
        save_btn: 'Save Face',
        revert_btn: 'Revert',
        export_btn: 'Export Face',
        source_code: 'Source Code',
        variations_title: 'Variations',
        choose_preset: 'Choose Face Target',
        loading: 'Generating Visual Face...',
        error_occured: 'An error occurred during generation.',
        speech_dictate: 'Speech Dictation',
        codex_title: 'The Celestial Codex 📖',
        codex_welcome: 'Welcome to SEN Workshop. You are designing complete visual faces for SEN Light Novels—specifically the Reader Chamber and the Living Codex.',
        codex_secret_title: 'The Power of Face Families 🌌',
        codex_secret_desc1: 'Single-surface modes generate visual faces for either the Reader Chamber or the Living Codex.',
        codex_secret_desc2: 'Select Face Family mode to generate three complete family directions simultaneously. Each direction contains a paired Reader Chamber face and Living Codex face created from the same shared visual DNA.',
        codex_family_dir1: 'Family Direction 1',
        codex_family_dir1_desc: 'Coordinated theme direction 1',
        codex_family_dir2: 'Family Direction 2',
        codex_family_dir2_desc: 'Coordinated theme direction 2',
        codex_presets_title: 'Visual Face Targets',
        codex_presets_desc: 'SEN Workshop supports three visual face generation modes:',
        codex_preset_free: 'Freeform',
        codex_preset_free_desc: 'Unstructured prompt generation.',
        codex_preset_icon: 'Reader Chamber',
        codex_preset_icon_desc: 'Coordinated visual theme for long-form reading, atmospheric palette, typography, audio narration, and scene scoring controls.',
        codex_preset_player: 'Living Codex',
        codex_preset_player_desc: 'Coordinated visual theme for lore encyclopedia, character entries, artifacts, beasts, factions, locations, and world knowledge.',
        codex_preset_family: 'Face Family',
        codex_preset_family_desc: 'Three complete family directions pairing coordinated Reader Chamber and Living Codex faces sharing one visual DNA.',
        codex_preset_plugin: 'Living Codex',
        codex_preset_plugin_desc: 'Interactive lore encyclopedia and world index.',
        codex_preset_deco: 'Reader Chamber',
        codex_preset_deco_desc: 'Long-form reading experience and typography system.',
        codex_footer: 'Crafted for the Celestial Library of SEN Light Novels.'
    },
    es: {
        app_title: 'SEN Workshop',
        app_sub: 'Faces visuales para SEN Light Novels (Cámara de Lectura y Códice Viviente)',
        created_by: 'Creado para SEN Light Novels',
        face_family_title: 'Familia de Faces',
        face_family_sub: 'Temas visuales coordinados para Cámara de Lectura y Códice Viviente',
        settings_title: 'Configuración',
        library_title: 'Biblioteca',
        how_to_use: 'Cómo usar',
        exit_error: 'Reiniciar / Salir',
        gen_failed: 'Generación Fallida',
        pres_select: 'Selecciona una face...',
        btn_send: 'Generar Face',
        vibe_dna: 'Personalizador ADN de Estilo',
        saved_to_lib: '¡Face guardada en la Biblioteca!',
        no_components: 'No hay faces guardadas aún.',
        save_btn: 'Guardar Face',
        revert_btn: 'Revertir',
        export_btn: 'Exportar Face',
        source_code: 'Código Fuente',
        variations_title: 'Variaciones',
        choose_preset: 'Elegir Objetivo de Face',
        loading: 'Generando Face Visual...',
        error_occured: 'Ocurrió un error durante la generación.',
        speech_dictate: 'Dictado por voz',
        codex_title: 'El Códice Celestial 📖',
        codex_welcome: 'Bienvenido a SEN Workshop. Diseñas faces visuales completas para SEN Light Novels: la Cámara de Lectura y el Códice Viviente.',
        codex_secret_title: 'El Poder de las Familias de Faces 🌌',
        codex_secret_desc1: 'Los modos de una superficie generan faces para la Cámara de Lectura o el Códice Viviente.',
        codex_secret_desc2: 'Selecciona el modo Familia de Faces para generar tres direcciones familiares completas. Cada dirección empareja una face de la Cámara de Lectura y una face del Códice Viviente con el mismo ADN visual.',
        codex_family_dir1: 'Dirección Familiar 1',
        codex_family_dir1_desc: 'Dirección de tema coordinado 1',
        codex_family_dir2: 'Dirección Familiar 2',
        codex_family_dir2_desc: 'Dirección de tema coordinado 2',
        codex_presets_title: 'Objetivos de Face Visual',
        codex_presets_desc: 'SEN Workshop admite tres modos de generación:',
        codex_preset_free: 'Forma Libre',
        codex_preset_free_desc: 'Generación libre basada en prompts.',
        codex_preset_icon: 'Cámara de Lectura',
        codex_preset_icon_desc: 'Tema visual coordinado para lectura inmersiva, paleta atmosférica, tipografía y controles de narrador.',
        codex_preset_player: 'Códice Viviente',
        codex_preset_player_desc: 'Tema visual coordinado para la enciclopedia de lore, personajes, artefactos, bestias y facciones.',
        codex_preset_family: 'Familia de Faces',
        codex_preset_family_desc: 'Tres direcciones familiares completas que coordinan faces de Cámara de Lectura y Códice Viviente.',
        codex_preset_plugin: 'Códice Viviente',
        codex_preset_plugin_desc: 'Enciclopedia de lore interactiva e índice de conocimiento.',
        codex_preset_deco: 'Cámara de Lectura',
        codex_preset_deco_desc: 'Experiencia de lectura y tipografía.',
        codex_footer: 'Creado para la Biblioteca Celestial de SEN Light Novels.'
    },
    ja: {
        app_title: 'SEN Workshop',
        app_sub: 'SEN Light Novels（リーダーチェンバー＆リビングコーデックス）用ビジュアルフェイス',
        created_by: 'SEN Light Novels のために作成',
        face_family_title: 'フェイスファミリー',
        face_family_sub: 'リーダーチェンバー＆リビングコーデックス用統合テーマ',
        settings_title: '設定',
        library_title: 'ライブラリ',
        how_to_use: '使い方',
        exit_error: '最初からやり直す / 終了',
        gen_failed: '生成に失敗しました',
        pres_select: 'フェイスを選択...',
        btn_send: 'フェイスを生成',
        vibe_dna: 'スタイルDNAカスタマイザー',
        saved_to_lib: 'ビジュアルフェイスがライブラリに保存されました！',
        no_components: '保存されたフェイスはまだありません。',
        save_btn: 'フェイスを保存',
        revert_btn: '元に戻す',
        export_btn: '書き出し',
        source_code: 'ソースコード',
        variations_title: 'バリエーション',
        choose_preset: 'ターゲットの選択',
        loading: 'ビジュアルフェイス生成中...',
        error_occured: '生成中にエラーが発生しました。',
        speech_dictate: '音声入力',
        codex_title: '天体のコーデックス 📖',
        codex_welcome: 'SEN Workshopへようこそ。SEN Light Novels アプリのリーダーチェンバーおよびリビングコーデックスのビジュアルフェイスを設計します。',
        codex_secret_title: 'フェイスファミリーの力 🌌',
        codex_secret_desc1: '単一サーフェスモードは読書室またはリビングコーデックスのいずれかのフェイスを生成します。',
        codex_secret_desc2: 'フェイスファミリーモードを選択すると、3つの完全なファミリー方向性を生成します。各方向性は同じ視覚DNAから作成されたペアのフェイスを含みます。',
        codex_family_dir1: 'ファミリー方向 1',
        codex_family_dir1_desc: '統合テーマ方向 1',
        codex_family_dir2: 'ファミリー方向 2',
        codex_family_dir2_desc: '統合テーマ方向 2',
        codex_presets_title: 'ビジュアルフェイス ターゲット',
        codex_presets_desc: 'SEN Workshop は3つの生成モードをサポートしています：',
        codex_preset_free: 'フリーフォーム',
        codex_preset_free_desc: '自由なプロンプト生成。',
        codex_preset_icon: 'リーダーチェンバー',
        codex_preset_icon_desc: '長文読書、雰囲気、タイポグラフィ、オーディオナレーション、スコアリングコントロールの統合テーマ。',
        codex_preset_player: 'リビングコーデックス',
        codex_preset_player_desc: '伝承百科事典、キャラクター、アーティファクト、魔獣、派閥、世界の知識の統合テーマ。',
        codex_preset_family: 'フェイスファミリー',
        codex_preset_family_desc: 'リーダーチェンバーとリビングコーデックスを統合する3つのファミリー方向性。',
        codex_preset_plugin: 'リビングコーデックス',
        codex_preset_plugin_desc: 'インタラクティブな世界観インデックス。',
        codex_preset_deco: 'リーダーチェンバー',
        codex_preset_deco_desc: '読書体験とタイポグラフィシステム。',
        codex_footer: 'SEN Light Novels Celestial Library のために構築。'
    },
    fr: {
        app_title: 'SEN Workshop',
        app_sub: 'Faces visuelles pour SEN Light Novels (Chambre de Lecture & Codex Vivant)',
        created_by: 'Créé pour SEN Light Novels',
        face_family_title: 'Famille de Faces',
        face_family_sub: 'Thèmes visuels coordonnés pour Chambre de Lecture & Codex Vivant',
        settings_title: 'Paramètres',
        library_title: 'Bibliothèque',
        how_to_use: 'Guide d\'utilisation',
        exit_error: 'Recommencer / Quitter',
        gen_failed: 'Échec de la Génération',
        pres_select: 'Sélectionner une face...',
        btn_send: 'Générer la Face',
        vibe_dna: 'Personnalisateur d\'ADN de Style',
        saved_to_lib: 'Face visuelle enregistrée dans la bibliothèque !',
        no_components: 'Aucune face visuelle enregistrée.',
        save_btn: 'Enregistrer la Face',
        revert_btn: 'Restaurer',
        export_btn: 'Exporter la Face',
        source_code: 'Code Source',
        variations_title: 'Variations',
        choose_preset: 'Choisir la Cible',
        loading: 'Génération de la Face Visuelle...',
        error_occured: 'Une erreur est survenue pendant la génération.',
        speech_dictate: 'Dictée vocale',
        codex_title: 'Le Codex Céleste 📖',
        codex_welcome: 'Bienvenue sur SEN Workshop. Créez des faces visuelles complètes pour SEN Light Novels (Chambre de Lecture et Codex Vivant).',
        codex_secret_title: 'Le Pouvoir des Familles de Faces 🌌',
        codex_secret_desc1: 'Les modes à surface unique génèrent des faces pour la Chambre de Lecture ou le Codex Vivant.',
        codex_secret_desc2: 'Sélectionnez le mode Famille de Faces pour générer trois directions complètes. Chaque direction associe une face de Chambre de Lecture et une face de Codex Vivant partageant le même ADN visuel.',
        codex_family_dir1: 'Direction Familiale 1',
        codex_family_dir1_desc: 'Direction de thème coordonné 1',
        codex_family_dir2: 'Direction Familiale 2',
        codex_family_dir2_desc: 'Direction de thème coordonné 2',
        codex_presets_title: 'Cibles de Face Visuelle',
        codex_presets_desc: 'SEN Workshop prend en charge trois modes de génération :',
        codex_preset_free: 'Forme Libre',
        codex_preset_free_desc: 'Génération libre.',
        codex_preset_icon: 'Chambre de Lecture',
        codex_preset_icon_desc: 'Thème visuel coordonné pour la lecture immersive, la typographie, l\'atmosphère et la narration audio.',
        codex_preset_player: 'Codex Vivant',
        codex_preset_player_desc: 'Thème visuel coordonné pour l\'encyclopédie du lore, les personnages, artefacts, créatures et factions.',
        codex_preset_family: 'Famille de Faces',
        codex_preset_family_desc: 'Trois directions familiales associant des faces de Chambre de Lecture et Codex Vivant.',
        codex_preset_plugin: 'Codex Vivant',
        codex_preset_plugin_desc: 'Encyclopédie du lore interactive.',
        codex_preset_deco: 'Chambre de Lecture',
        codex_preset_deco_desc: 'Expérience de lecture et typographie.',
        codex_footer: 'Créé pour la Bibliothèque Céleste de SEN Light Novels.'
    },
    pt: {
        app_title: 'SEN Workshop',
        app_sub: 'Visual faces para SEN Light Novels (Câmara de Leitura & Codex Vivo)',
        created_by: 'Criado para SEN Light Novels',
        face_family_title: 'Família de Faces',
        face_family_sub: 'Temas visuais coordenados para Câmara de Leitura e Codex Vivo',
        settings_title: 'Configurações',
        library_title: 'Biblioteca',
        how_to_use: 'Como Usar',
        exit_error: 'Recomeçar / Sair',
        gen_failed: 'Falha na Geração',
        pres_select: 'Selecione uma face...',
        btn_send: 'Gerar Face',
        vibe_dna: 'Customizador de DNA de Estilo',
        saved_to_lib: 'Face visual salva na Biblioteca!',
        no_components: 'Nenhuma face visual salva ainda.',
        save_btn: 'Salvar Face',
        revert_btn: 'Reverter',
        export_btn: 'Exportar Face',
        source_code: 'Código Fonte',
        variations_title: 'Variações',
        choose_preset: 'Escolher Alvo da Face',
        loading: 'Gerando Face Visual...',
        error_occured: 'Ocorreu um erro durante a geração.',
        speech_dictate: 'Ditado de voz',
        codex_title: 'O Codex Celestial 📖',
        codex_welcome: 'Bem-vindo ao SEN Workshop. Desenvolva faces visuais completas para o SEN Light Novels (Câmara de Leitura e Codex Vivo).',
        codex_secret_title: 'O Poder das Famílias de Faces 🌌',
        codex_secret_desc1: 'Os modos de superfície única geram faces para a Câmara de Leitura ou o Codex Vivo.',
        codex_secret_desc2: 'Selecione o modo Família de Faces para gerar três direções familiares completas. Cada direção combina uma face da Câmara de Leitura e uma do Codex Vivo com o mesmo DNA visual.',
        codex_family_dir1: 'Direção Familiar 1',
        codex_family_dir1_desc: 'Direção de tema coordenado 1',
        codex_family_dir2: 'Direção Familiar 2',
        codex_family_dir2_desc: 'Direção de tema coordenado 2',
        codex_presets_title: 'Alvos de Face Visual',
        codex_presets_desc: 'SEN Workshop suporta três modos de geração:',
        codex_preset_free: 'Forma Livre',
        codex_preset_free_desc: 'Geração livre.',
        codex_preset_icon: 'Câmara de Leitura',
        codex_preset_icon_desc: 'Tema visual coordenado para leitura imersiva, tipografia, atmosfera e controles de narração.',
        codex_preset_player: 'Codex Vivo',
        codex_preset_player_desc: 'Tema visual coordenado para enciclopédia do universo, personagens, artefatos, feras e facções.',
        codex_preset_family: 'Família de Faces',
        codex_preset_family_desc: 'Três direções familiares combinando faces de Câmara de Leitura e Codex Vivo.',
        codex_preset_plugin: 'Codex Vivo',
        codex_preset_plugin_desc: 'Enciclopédia interativa do universo.',
        codex_preset_deco: 'Câmara de Leitura',
        codex_preset_deco_desc: 'Experiência de leitura e sistema de tipografia.',
        codex_footer: 'Criado para a Biblioteca Celestial do SEN Light Novels.'
    }
};

export const getLanguage = (): Language => {
    return (localStorage.getItem('sea_language') as Language) || 'en';
};

export const setLanguage = (lang: Language): void => {
    localStorage.setItem('sea_language', lang);
};

export function useLanguage() {
    const [lang, setLangState] = useState<Language>(getLanguage);

    const changeLanguage = (newLang: Language) => {
        setLanguage(newLang);
        setLangState(newLang);
        window.dispatchEvent(new Event('languagechange'));
    };

    useEffect(() => {
        const handleLangChange = () => {
            setLangState(getLanguage());
        };
        window.addEventListener('languagechange', handleLangChange);
        return () => window.removeEventListener('languagechange', handleLangChange);
    }, []);

    const t = (key: string): string => {
        const dict = LOCALIZATION_DICTS[lang] || LOCALIZATION_DICTS.en;
        return dict[key] || LOCALIZATION_DICTS.en[key] || key;
    };

    return { lang, changeLanguage, t };
}
