import { useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'ja' | 'fr' | 'pt';

export const LANGUAGE_NAMES: Record<Language, string> = {
    en: 'English (EN)',
    es: 'Español (ES)',
    ja: '日本語 (JA)',
    fr: 'Français (FR)',
    pt: 'Português (PT)'
};

// Humorous, elegant, clear localization values
export const LOCALIZATION_DICTS: Record<Language, Record<string, string>> = {
    en: {
        app_title: 'SEN Workshop',
        app_sub: 'Creative reading UI generation for Light Novels',
        created_by: 'Created for SEN Light Novels',
        dual_mode_on: 'Dual Mode: ON',
        dual_mode_off: 'Dual Mode: OFF',
        settings_title: 'Settings',
        library_title: 'Library',
        how_to_use: 'How to Use',
        fuse_master: 'Fuse Master Component',
        exit_error: 'Start Over / Exit',
        gen_failed: 'Generation Failed',
        pres_select: 'Select a preset...',
        btn_send: 'Generate',
        vibe_dna: 'Vibe DNA Customizer',
        saved_to_lib: 'Component saved to Library!',
        no_components: 'No saved components yet.',
        save_btn: 'Save Component',
        revert_btn: 'Revert',
        export_btn: 'Export Component',
        source_code: 'Source Code',
        variations_title: 'Variations',
        choose_preset: 'Choose Preset Theme',
        loading: 'Generating...',
        error_occured: 'An error occurred during generation.',
        speech_dictate: 'Speech Dictation',
        codex_title: 'The Living Codex 📖',
        codex_welcome: 'Welcome to SEN Workshop. You are currently commanding a highly advanced client-side AI generator. To maximize your creative design throughput for SEN Light Novels, let\'s unlock the secrets of our core engines.',
        codex_secret_title: 'The Secret of Dual Mode',
        codex_secret_desc1: 'Standard mode generates alternate iterations based on a single config profile. Safe. Predictable. Boring.',
        codex_secret_desc2: 'Toggle Dual Mode: ON on the bottom bar to split the generative timeline. It executes two streams in parallel using completely independent parameters:',
        codex_universe_a: 'Universe A',
        codex_universe_a_desc: 'Built using profile settings A',
        codex_universe_b: 'Universe B',
        codex_universe_b_desc: 'Built using profile settings B',
        codex_fusion_title: 'The Fusion Chamber Activated',
        codex_fusion_desc: 'When generation completes in Dual Mode, deselect individual cards so both alternates lie on-screen. Magic happens! A button labeled Fuse Master Component will materialise. Hit it, and the AI will dissect both structures, extracting the absolute best traits from each to forge a singular, fused masterpiece.',
        codex_presets_title: 'Quantum Component Presets',
        codex_presets_desc: 'Don\'t just pray to the algorithm. Force structural intent by selecting a preset from the dock. Here is how they influence reality:',
        codex_preset_free: 'Freeform',
        codex_preset_free_desc: 'The Wild West. Generates based purely on whatever chaotic prompt you feed it. Zero guidelines, complete creative autonomy.',
        codex_preset_icon: 'Reader Chamber',
        codex_preset_icon_desc: 'Ideal for reading layouts, typography systems, and elegant story presentation.',
        codex_preset_player: 'Living Codex',
        codex_preset_player_desc: 'Built for interactive encyclopedias, character lore profiles, and magical systems.',
        codex_preset_plugin: 'Book Gallery & Navigation',
        codex_preset_plugin_desc: 'Converts the canvas into beautiful library views, table of contents, and bookmark systems.',
        codex_preset_deco: 'Typography Panel',
        codex_preset_deco_desc: 'Compact settings panels for adjusting fonts, line spacing, and themes in a reading app.',
        codex_footer: 'Disclaimer: Merging timeline alternate realities may result in highly addictive UI iterations. Use responsibly.'
    },
    es: {
        app_title: 'SEN Workshop',
        app_sub: 'Generación creativa de UI musical en un instante',
        created_by: 'Creado por SEIHouse',
        dual_mode_on: 'Modo Dual: ACTIVO',
        dual_mode_off: 'Modo Dual: DESACTIVADO',
        settings_title: 'Configuración',
        library_title: 'Biblioteca',
        how_to_use: 'Cómo usar',
        fuse_master: 'Fusionar Componente Maestro',
        exit_error: 'Reiniciar / Salir',
        gen_failed: 'Generación Fallida',
        pres_select: 'Selecciona una preconfiguración...',
        btn_send: 'Generar',
        vibe_dna: 'Personalizador de ADN de Vibe',
        saved_to_lib: '¡Componente guardado en la Biblioteca!',
        no_components: 'No hay componentes guardados aún.',
        save_btn: 'Guardar Componente',
        revert_btn: 'Revertir',
        export_btn: 'Exportar Componente',
        source_code: 'Código Fuente',
        variations_title: 'Variaciones',
        choose_preset: 'Elegir Tema Predeterminado',
        loading: 'Generando...',
        error_occured: 'Ocurrió un error durante la generación.',
        speech_dictate: 'Dictado por voz',
        codex_title: 'El Códice Galáctico 🛸',
        codex_welcome: 'Bienvenido a SEN Workshop. Actualmente comandas un generador de IA del lado del cliente altamente avanzado. Para maximizar tu rendimiento de diseño cósmico, desbloqueemos los secretos de nuestros motores principales.',
        codex_secret_title: 'El Secreto del Modo Dual',
        codex_secret_desc1: 'El modo estándar genera iteraciones alternativas basadas en un único perfil de configuración. Seguro. Predictivo. Aburrido.',
        codex_secret_desc2: 'Activa Modo Dual: ON en la barra inferior para dividir la línea de tiempo generativa. Ejecuta dos transmisiones en paralelo utilizando parámetros completamente independientes:',
        codex_universe_a: 'Universo A',
        codex_universe_a_desc: 'Construido utilizando la configuración del perfil A',
        codex_universe_b: 'Universo B',
        codex_universe_b_desc: 'Construido utilizando la configuración del perfil B',
        codex_fusion_title: 'La Cámara de Fusión Activada',
        codex_fusion_desc: 'Cuando finaliza la generación en Modo Dual, deselecciona las tarjetas individuales para que ambas alternativas queden en pantalla. ¡Ocurre la magia! Aparecerá un botón llamado "Fusionar Componente Maestro". Presiónalo, y la IA diseccionará ambas estructuras, extrayendo las mejores características de cada una para forjar una obra maestra singular fusionada.',
        codex_presets_title: 'Ajustes Preestablecidos Cuánticos',
        codex_presets_desc: 'No solo le reces al algoritmo. Fuerza una intención estructural seleccionando una preconfiguración del panel. Así es como influyen en la realidad:',
        codex_preset_free: 'Forma Libre',
        codex_preset_free_desc: 'El Salvaje Oeste. Genera basándose puramente en cualquier instrucción caótica que le des. Cero pautas, autonomía creativa total.',
        codex_preset_icon: 'Icono Personalizado y Mini Insignia',
        codex_preset_icon_desc: 'Ideal para microinterfaces y estadísticas clave como BPM, Tonalidad o etiquetas. Diseñado para encajar perfectamente en rejillas compactas y adaptables.',
        codex_preset_player: 'Reproductor, Deslizador y Formas de Onda',
        codex_preset_player_desc: 'Creado para activar un placer auditivo. Perfecto para reproductores de música de sensación táctil física, formas de onda y selectores de audio interactivos.',
        codex_preset_plugin: 'Módulo de Plugin y Ajustes Rápidos',
        codex_preset_plugin_desc: 'Convierte el lienzo en controles de sintetizador modular de alta tecnología, diales y deslizadores translúcidos. El patio de juegos interactivo definitivo.',
        codex_preset_deco: 'Efecto Decorativo',
        codex_preset_deco_desc: 'No tiene ningún propósito práctico pero se ve increíblemente bien. Ideal para animaciones ambientales satisfactorias o destellos de audio futuristas.',
        codex_footer: 'Descargo de responsabilidad: Fusionar realidades alternativas del continuo del tiempo puede resultar en iteraciones de UI extremadamente adictivas. Use con moderación.'
    },
    ja: {
        app_title: 'SEN Workshop',
        app_sub: '一瞬でクリエイティブな音楽UIを生成',
        created_by: 'SEIHouseによる制作',
        dual_mode_on: 'デュアルモード: オン',
        dual_mode_off: 'デュアルモード: オフ',
        settings_title: '設定',
        library_title: 'ライブラリ',
        how_to_use: '使い方',
        fuse_master: 'マスターコンポーネントを融合',
        exit_error: '最初からやり直す / 終了',
        gen_failed: '生成に失敗しました',
        pres_select: 'プリセットを選択...',
        btn_send: '生成する',
        vibe_dna: 'バイブDNAカスタマイザー',
        saved_to_lib: 'ライブラリに保存されました！',
        no_components: '保存されたコンポーネントはまだありません。',
        save_btn: 'コンポーネントを保存',
        revert_btn: '元に戻す',
        export_btn: '書き出し',
        source_code: 'ソースコード',
        variations_title: 'バリエーション',
        choose_preset: 'プリセットテーマの選択',
        loading: '生成中...',
        error_occured: '生成中にエラーが発生しました。',
        speech_dictate: '音声入力',
        codex_title: '銀河系コーデックス 🛸',
        codex_welcome: 'SEN Workshopへようこそ。あなたは現在、超高度なクライアントサイドAIジェネレーターを指揮しています。宇宙的なデザインスループットを最大化するために、コアエンジンの秘密を解き明かしましょう。',
        codex_secret_title: 'デュアルモードの秘密',
        codex_secret_desc1: '標準モードは、単一の設定プロファイルに基づいて代替世代を生成します。安全、予測可能、つまり「平凡」です。',
        codex_secret_desc2: '下部バーの「デュアルモード: オン」を切り替えて、生成タイムラインを分岐させます。完全に独立したパラメーターを使用して、2つのストリームを並行して実行します：',
        codex_universe_a: 'ユニバース A',
        codex_universe_a_desc: 'プロファイル設定Aを使用して構築',
        codex_universe_b: 'ユニバース B',
        codex_universe_b_desc: 'プロファイル設定Bを使用して構築',
        codex_fusion_title: '融合チャンバー発動',
        codex_fusion_desc: 'デュアルモードで生成が完了したら、個々のカードの選択を解除して、両方の代替案を画面に並べます。ここで魔法が起きます！「マスターコンポーネントを融合」というボタンが出現します。それを押すと、AIが両方の構造を分析し、それぞれから絶対的な最良の特性を抽出して、唯一無二の融合傑作を鍛え上げます。',
        codex_presets_title: '量子コンポーネントプリセット',
        codex_presets_desc: '暗黙のアルゴリズムに祈るだけではいけません。ドックからプリセットを選択して、構造的な意思を強制します。プレテストが現実にどのように影響するかは以下の通りです：',
        codex_preset_free: 'フリーフォーム',
        codex_preset_free_desc: 'ワイルド・ウエスト。あなたが投入するいかなる混沌としたプロンプトにも純粋に基づいて生成されます。ガイドラインは一切なく、完全な創造的自律性があります。',
        codex_preset_icon: 'カスタムアイコン＆ミニバッジ',
        codex_preset_icon_desc: 'マイクロインターフェースや、BPM、キー、タグなどの重要な統計に最適です。コンパクトでレスポンシブなグリッドに美しくフィットするように設計されています。',
        codex_preset_player: '再生ボタン、スクラバー、＆波形',
        codex_preset_player_desc: '音の満足感をトリガーするために作られました。立体的な感触のミュージックプレーヤー、波形、クリック可能なオーディオ切り替えに最適です。',
        codex_preset_plugin: 'プラグインタイル＆ミニ設定',
        codex_preset_plugin_desc: 'キャンバスをハイテクでモジュール式のシンセサイザーコントロール、ダイヤル、そしてグラスのような調整スライダーに変換します。究極の触覚遊び場。',
        codex_preset_deco: '装飾的な効果',
        codex_preset_deco_desc: '実用的な目的は一切ありませんが、ものすごくクールに見えます。満足のいくアンビエントアニメーションや近未来的なオーディオーディオグリーマーに最適です。',
        codex_footer: '免責事項：時間軸の並行現実を融合すると、極めて中毒性の高いUIの反復が生じる恐れがあります。計画的にご利用ください。'
    },
    fr: {
        app_title: 'SEN Workshop',
        app_sub: 'Génération créative d\'UI musicales en un clin d\'œil',
        created_by: 'Créé par SEIHouse',
        dual_mode_on: 'Mode Dual: ACTIVÉ',
        dual_mode_off: 'Mode Dual: DÉSACTIVÉ',
        settings_title: 'Paramètres',
        library_title: 'Bibliothèque',
        how_to_use: 'Guide d\'utilisation',
        fuse_master: 'Fusionner en Composant Maître',
        exit_error: 'Recommencer / Quitter',
        gen_failed: 'Échec de la Génération',
        pres_select: 'Sélectionner un préréglage...',
        btn_send: 'Générer',
        vibe_dna: 'Personnalisateur d\'ADN Vibe',
        saved_to_lib: 'Composant enregistré dans la bibliothèque !',
        no_components: 'Aucun composant enregistré pour le moment.',
        save_btn: 'Enregistrer le Composant',
        revert_btn: 'Restaurer',
        export_btn: 'Exporter le Composant',
        source_code: 'Code Source',
        variations_title: 'Variations',
        choose_preset: 'Choisir le Thème',
        loading: 'Génération...',
        error_occured: 'Une erreur est survenue pendant la génération.',
        speech_dictate: 'Dictée vocale',
        codex_title: 'Le Codex Galactique 🛸',
        codex_welcome: 'Bienvenue sur SEN Workshop. Vous commandez actuellement un générateur d\'IA client hautement sophistiqué. Pour maximiser votre débit de création cosmique, perçons les secrets de nos moteurs principaux.',
        codex_secret_title: 'Le Secret du Mode Dual',
        codex_secret_desc1: 'Le mode standard génère des itérations alternatives basées sur un seul profil de configuration. Sûr. Prévisible. Ennuyeux.',
        codex_secret_desc2: 'Activez "Mode Dual: ACTIVÉ" sur la barre inférieure pour diviser la ligne temporelle générative. Il exécute deux flux en parallèle avec des paramètres totalement indépendants :',
        codex_universe_a: 'Univers A',
        codex_universe_a_desc: 'Créé avec les paramètres du profil A',
        codex_universe_b: 'Univers B',
        codex_universe_b_desc: 'Créé avec les paramètres du profil B',
        codex_fusion_title: 'Chambre de Fusion Activée',
        codex_fusion_desc: 'Une fois la génération terminée en Mode Dual, désélectionnez les cartes individuelles pour que les deux alternatives s\'affichent à l\'écran. La magie opère ! Un bouton "Fusionner en Composant Maître" matérialise. Cliquez dessus pour que l\'IA dissèque les deux structures, combinant le meilleur de chacune pour forger un chef-d\'œuvre unique.',
        codex_presets_title: 'Préréglages Quantiques',
        codex_presets_desc: 'Ne priez pas seulement l\'algorithme. Imposez une intention structurelle en sélectionnant un préréglage. Voici comment ils influencent la réalité :',
        codex_preset_free: 'Forme Libre',
        codex_preset_free_desc: 'Le Far West. Généré purement à partir de vos prompts les plus chaotiques. Zéro contrainte, autonomie créative totale.',
        codex_preset_icon: 'Icône Personnalisée & Mini Badge',
        codex_preset_icon_desc: 'Idéal pour les micro-interfaces et les stats clés (BPM, tonalités ou labels). Conçu pour s\'intégrer harmonieusement sur des grilles compactes.',
        codex_preset_player: 'Bouton de Lecture, Scrubber & Formes d\'Onde',
        codex_preset_player_desc: 'Conçu pour déclencher un plaisir acoustique. Parfait pour les lecteurs tactiles, les formes d\'onde et les boutons cliquables.',
        codex_preset_plugin: 'Module de Plugin & Mini Réglages',
        codex_preset_plugin_desc: 'Transforme le canevas en un synthétiseur modulaire high-tech, avec boutons rotatifs et curseurs translucides. Le terrain de jeu tactile suprême.',
        codex_preset_deco: 'Effet Décoratif',
        codex_preset_deco_desc: 'Totalement inutile mais incroyablement cool. Idéal pour des animations d\'ambiance fluides ou des lueurs audio futuristes.',
        codex_footer: 'Avertissement : Fusionner des réalités temporelles alternatives peut provoquer une addiction sévère aux itérations d\'interfaces. À consommer avec modération.'
    },
    pt: {
        app_title: 'SEN Workshop',
        app_sub: 'Geração criativa de UI de música em um piscar de olhos',
        created_by: 'Criado por SEIHouse',
        dual_mode_on: 'Modo Dual: ATIVO',
        dual_mode_off: 'Modo Dual: DESATIVADO',
        settings_title: 'Configurações',
        library_title: 'Biblioteca',
        how_to_use: 'Como Usar',
        fuse_master: 'Fundir Componente Mestre',
        exit_error: 'Recomeçar / Sair',
        gen_failed: 'Falha na Geração',
        pres_select: 'Selecione predefinição...',
        btn_send: 'Gerar',
        vibe_dna: 'Customizador de DNA Vibe',
        saved_to_lib: 'Componente salvo na Biblioteca!',
        no_components: 'Nenhum componente salvo ainda.',
        save_btn: 'Salvar Componente',
        revert_btn: 'Reverter',
        export_btn: 'Exportar Componente',
        source_code: 'Código Fonte',
        variations_title: 'Variações',
        choose_preset: 'Escolher Tema',
        loading: 'Gerando...',
        error_occured: 'Ocorreu um erro durante a geração.',
        speech_dictate: 'Ditado de voz',
        codex_title: 'O Codex Galáctico 🛸',
        codex_welcome: 'Bem-vindo ao SEN Workshop. Você está comandando um gerador de IA extremamente sofisticado do lado do cliente. Para maximizar sua capacidade de criação cósmica, vamos desvendar os segredos dos nossos motores centrais.',
        codex_secret_title: 'O Segredo do Modo Dual',
        codex_secret_desc1: 'O modo padrão gera iterações alternativas com base em um único perfil de configuração. Seguro. Previsível. Monótono.',
        codex_secret_desc2: 'Ative o Modo Dual na barra inferior para dividir a linha do tempo gerativa. Ele executa dois fluxos de geração em paralelo com parâmetros inteiramente independentes:',
        codex_universe_a: 'Universo A',
        codex_universe_a_desc: 'Gerado usando as configurações do perfil A',
        codex_universe_b: 'Universo B',
        codex_universe_b_desc: 'Gerado usando as configurações do perfil B',
        codex_fusion_title: 'Câmara de Fusão Ativada',
        codex_fusion_desc: 'Quando a geração for concluída no Modo Dual, desmarque os cards para que ambos os alternativos apareçam na tela. A mágica acontece! Um botão escrito "Fundir Componente Mestre" aparecerá. Clique nele para a IA dissecar ambas as estruturas, integrando as melhores características para forjar uma obra-prima unificada.',
        codex_presets_title: 'Predefinições Quânticas',
        codex_presets_desc: 'Não ore apenas ao algoritmo. Force a estrutura selecionando uma predefinição. Veja o impacto de cada uma na realidade:',
        codex_preset_free: 'Forma Livre',
        codex_preset_free_desc: 'O Velho Oeste. Gera baseado 100% nas instruções mais caóticas que fornecer. Autonomia criativa absoluta.',
        codex_preset_icon: 'Ícone Customizado & Mini Badge',
        codex_preset_icon_desc: 'Perfeito para micro-interfaces e estatísticas essenciais como BPM, tom de música ou etiquetas.',
        codex_preset_player: 'Botão Player, Scrubber, & Ondas Sonoras',
        codex_preset_player_desc: 'Criado para satisfação auditiva física. Reprodutores de áudio táteis interativos com belas ondas sonoras.',
        codex_preset_plugin: 'Painel de Plugin & Mini Controles',
        codex_preset_plugin_desc: 'Transforma a tela em controles de sintetizadores modernos, potenciômetros e sliders de vidro fosco.',
        codex_preset_deco: 'Efeito Decorativo',
        codex_preset_deco_desc: 'Não serve para nada útil, mas é extremamente estiloso. Perfeito para animações de ondas de áudio futuristas luminosas.',
        codex_footer: 'Aviso legal: Fusões de realidades paralelas podem causar dependência extrema em web design cósmico. Use com moderação.'
    }
};

export const getLanguage = (): Language => {
    return (localStorage.getItem('sea_language') as Language) || 'en';
};

export const setLanguage = (lang: Language): void => {
    localStorage.setItem('sea_language', lang);
};

export function useLanguage() {
    const [lang, setLangState] = useState<Language>(getLanguage);

    const changeLanguage = (newLang: Language) => {
        setLanguage(newLang);
        setLangState(newLang);
        window.dispatchEvent(new Event('languagechange'));
    };

    useEffect(() => {
        const handleLangChange = () => {
            setLangState(getLanguage());
        };
        window.addEventListener('languagechange', handleLangChange);
        return () => window.removeEventListener('languagechange', handleLangChange);
    }, []);

    const t = (key: string): string => {
        const dict = LOCALIZATION_DICTS[lang] || LOCALIZATION_DICTS.en;
        return dict[key] || LOCALIZATION_DICTS.en[key] || key;
    };

    return { lang, changeLanguage, t };
}
