import { useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'ja' | 'fr' | 'pt';

export const LANGUAGE_NAMES: Record<Language, string> = {
    en: 'English (EN)',
    es: 'Español (ES)',
    ja: '日本語 (JA)',
    fr: 'Français (FR)',
    pt: 'Português (PT)'
};

// Humorous, elegant, clear localization values
export const LOCALIZATION_DICTS: Record<Language, Record<string, string>> = {
    en: {
        app_title: 'SEN Workshop',
        app_sub: 'Visual faces for SEN Light Novels (Reader Chamber & Living Codex)',
        created_by: 'Created for SEN Light Novels',
        dual_mode_on: 'Dual Mode: ON',
        dual_mode_off: 'Dual Mode: OFF',
        settings_title: 'Settings',
        library_title: 'Library',
        how_to_use: 'How to Use',
        fuse_master: 'Fuse Master Visual Face',
        exit_error: 'Start Over / Exit',
        gen_failed: 'Generation Failed',
        pres_select: 'Select a face target...',
        btn_send: 'Generate Face',
        vibe_dna: 'Style DNA Customizer',
        saved_to_lib: 'Visual Face saved to Library!',
        no_components: 'No saved visual faces yet.',
        save_btn: 'Save Face',
        revert_btn: 'Revert',
        export_btn: 'Export Face',
        source_code: 'Source Code',
        variations_title: 'Variations',
        choose_preset: 'Choose Face Target',
        loading: 'Generating Visual Face...',
        error_occured: 'An error occurred during generation.',
        speech_dictate: 'Speech Dictation',
        codex_title: 'The Celestial Codex 📖',
        codex_welcome: 'Welcome to SEN Workshop. You are designing complete visual faces for the SEN Light Novels application—specifically the Reader Chamber and the Living Codex.',
        codex_secret_title: 'The Power of Dual Mode',
        codex_secret_desc1: 'Standard mode generates alternate iterations based on a single config profile.',
        codex_secret_desc2: 'Toggle Dual Mode: ON on the bottom bar to split the generative timeline. It executes two streams in parallel using independent parameters:',
        codex_universe_a: 'Universe A',
        codex_universe_a_desc: 'Built using profile settings A',
        codex_universe_b: 'Universe B',
        codex_universe_b_desc: 'Built using profile settings B',
        codex_fusion_title: 'The Fusion Chamber Activated',
        codex_fusion_desc: 'When generation completes in Dual Mode, deselect individual cards so both alternates lie on-screen. A button labeled Fuse Master Visual Face will appear. Hit it, and the AI will combine the best visual & structural traits into a single fused face theme.',
        codex_presets_title: 'Visual Face Targets',
        codex_presets_desc: 'SEN Workshop is focused on two complete face targets:',
        codex_preset_free: 'Freeform',
        codex_preset_free_desc: 'Unstructured prompt generation.',
        codex_preset_icon: 'Reader Chamber',
        codex_preset_icon_desc: 'Whole coordinated visual theme for long-form reading, atmospheric palette, typography, audio narration, and scene scoring controls.',
        codex_preset_player: 'Living Codex',
        codex_preset_player_desc: 'Whole coordinated visual theme for lore encyclopedia, character entries, artifacts, beasts, factions, locations, and world knowledge.',
        codex_preset_plugin: 'Living Codex',
        codex_preset_plugin_desc: 'Interactive lore encyclopedia and world index.',
        codex_preset_deco: 'Reader Chamber',
        codex_preset_deco_desc: 'Long-form reading experience and typography system.',
        codex_footer: 'Crafted for the Celestial Library of SEN Light Novels.'
    },
    es: {
        app_title: 'SEN Workshop',
        app_sub: 'Faces visuales para SEN Light Novels (Cámara de Lectura y Códice Viviente)',
        created_by: 'Creado para SEN Light Novels',
        dual_mode_on: 'Modo Dual: ACTIVO',
        dual_mode_off: 'Modo Dual: DESACTIVADO',
        settings_title: 'Configuración',
        library_title: 'Biblioteca',
        how_to_use: 'Cómo usar',
        fuse_master: 'Fusionar Face Maestra',
        exit_error: 'Reiniciar / Salir',
        gen_failed: 'Generación Fallida',
        pres_select: 'Selecciona una face...',
        btn_send: 'Generar Face',
        vibe_dna: 'Personalizador ADN de Estilo',
        saved_to_lib: '¡Face guardada en la Biblioteca!',
        no_components: 'No hay faces guardadas aún.',
        save_btn: 'Guardar Face',
        revert_btn: 'Revertir',
        export_btn: 'Exportar Face',
        source_code: 'Código Fuente',
        variations_title: 'Variaciones',
        choose_preset: 'Elegir Objetivo de Face',
        loading: 'Generando Face Visual...',
        error_occured: 'Ocurrió un error durante la generación.',
        speech_dictate: 'Dictado por voz',
        codex_title: 'El Códice Celestial 📖',
        codex_welcome: 'Bienvenido a SEN Workshop. Diseñas faces visuales completas para SEN Light Novels: la Cámara de Lectura y el Códice Viviente.',
        codex_secret_title: 'El Poder del Modo Dual',
        codex_secret_desc1: 'El modo estándar genera iteraciones alternativas basadas en un perfil único.',
        codex_secret_desc2: 'Activa Modo Dual: ON para dividir la línea de tiempo generativa en dos transmisiones paralelas:',
        codex_universe_a: 'Universo A',
        codex_universe_a_desc: 'Construido con el perfil A',
        codex_universe_b: 'Universo B',
        codex_universe_b_desc: 'Construido con el perfil B',
        codex_fusion_title: 'Cámara de Fusión Activada',
        codex_fusion_desc: 'Disecciona ambas estructuras para forjar una obra maestra singular fusionada.',
        codex_presets_title: 'Objetivos de Face Visual',
        codex_presets_desc: 'SEN Workshop se enfoca en dos faces completas:',
        codex_preset_free: 'Forma Libre',
        codex_preset_free_desc: 'Generación libre basada en prompts.',
        codex_preset_icon: 'Cámara de Lectura',
        codex_preset_icon_desc: 'Tema visual coordinado para lectura inmersiva, paleta atmosférica, tipografía y controles de narrador.',
        codex_preset_player: 'Códice Viviente',
        codex_preset_player_desc: 'Tema visual coordinado para la enciclopedia de lore, personajes, artefactos, bestias y facciones.',
        codex_preset_plugin: 'Códice Viviente',
        codex_preset_plugin_desc: 'Enciclopedia de lore interactiva e índice de conocimiento.',
        codex_preset_deco: 'Cámara de Lectura',
        codex_preset_deco_desc: 'Experiencia de lectura y tipografía.',
        codex_footer: 'Creado para la Biblioteca Celestial de SEN Light Novels.'
    },
    ja: {
        app_title: 'SEN Workshop',
        app_sub: 'SEN Light Novels（リーダーチェンバー＆リビングコーデックス）用ビジュアルフェイス',
        created_by: 'SEN Light Novels のために作成',
        dual_mode_on: 'デュアルモード: オン',
        dual_mode_off: 'デュアルモード: オフ',
        settings_title: '設定',
        library_title: 'ライブラリ',
        how_to_use: '使い方',
        fuse_master: 'マスターフェイスを融合',
        exit_error: '最初からやり直す / 終了',
        gen_failed: '生成に失敗しました',
        pres_select: 'フェイスを選択...',
        btn_send: 'フェイスを生成',
        vibe_dna: 'スタイルDNAカスタマイザー',
        saved_to_lib: 'ビジュアルフェイスがライブラリに保存されました！',
        no_components: '保存されたフェイスはまだありません。',
        save_btn: 'フェイスを保存',
        revert_btn: '元に戻す',
        export_btn: '書き出し',
        source_code: 'ソースコード',
        variations_title: 'バリエーション',
        choose_preset: 'ターゲットの選択',
        loading: 'ビジュアルフェイス生成中...',
        error_occured: '生成中にエラーが発生しました。',
        speech_dictate: '音声入力',
        codex_title: '天体のコーデックス 📖',
        codex_welcome: 'SEN Workshopへようこそ。SEN Light Novels アプリのリーダーチェンバーおよびリビングコーデックスのビジュアルフェイスを設計します。',
        codex_secret_title: 'デュアルモードの力',
        codex_secret_desc1: '標準モードは単一の設定に基づいて代替を生成します。',
        codex_secret_desc2: 'デュアルモードをオンにすると、2つの独立したストリームを並行して実行します：',
        codex_universe_a: 'ユニバース A',
        codex_universe_a_desc: 'プロファイル設定Aを使用して構築',
        codex_universe_b: 'ユニバース B',
        codex_universe_b_desc: 'プロファイル設定Bを使用して構築',
        codex_fusion_title: '融合チャンバー発動',
        codex_fusion_desc: 'デュアルモード完了時、両方の構造を融合して最良のビジュアルフェイスを生成します。',
        codex_presets_title: 'ビジュアルフェイス ターゲット',
        codex_presets_desc: 'SEN Workshop は2つの完全なフェイスに特化しています：',
        codex_preset_free: 'フリーフォーム',
        codex_preset_free_desc: '自由なプロンプト生成。',
        codex_preset_icon: 'リーダーチェンバー',
        codex_preset_icon_desc: '長文読書、雰囲気、タイポグラフィ、オーディオナレーション、スコアリングコントロールの統合テーマ。',
        codex_preset_player: 'リビングコーデックス',
        codex_preset_player_desc: '伝承百科事典、キャラクター、アーティファクト、魔獣、派閥、世界の知識の統合テーマ。',
        codex_preset_plugin: 'リビングコーデックス',
        codex_preset_plugin_desc: 'インタラクティブな世界観インデックス。',
        codex_preset_deco: 'リーダーチェンバー',
        codex_preset_deco_desc: '読書体験とタイポグラフィシステム。',
        codex_footer: 'SEN Light Novels Celestial Library のために構築。'
    },
    fr: {
        app_title: 'SEN Workshop',
        app_sub: 'Faces visuelles pour SEN Light Novels (Chambre de Lecture & Codex Vivant)',
        created_by: 'Créé pour SEN Light Novels',
        dual_mode_on: 'Mode Dual: ACTIVÉ',
        dual_mode_off: 'Mode Dual: DÉSACTIVÉ',
        settings_title: 'Paramètres',
        library_title: 'Bibliothèque',
        how_to_use: 'Guide d\'utilisation',
        fuse_master: 'Fusionner la Face Visuelle Maître',
        exit_error: 'Recommencer / Quitter',
        gen_failed: 'Échec de la Génération',
        pres_select: 'Sélectionner une face...',
        btn_send: 'Générer la Face',
        vibe_dna: 'Personnalisateur d\'ADN de Style',
        saved_to_lib: 'Face visuelle enregistrée dans la bibliothèque !',
        no_components: 'Aucune face visuelle enregistrée.',
        save_btn: 'Enregistrer la Face',
        revert_btn: 'Restaurer',
        export_btn: 'Exporter la Face',
        source_code: 'Code Source',
        variations_title: 'Variations',
        choose_preset: 'Choisir la Cible',
        loading: 'Génération de la Face Visuelle...',
        error_occured: 'Une erreur est survenue pendant la génération.',
        speech_dictate: 'Dictée vocale',
        codex_title: 'Le Codex Céleste 📖',
        codex_welcome: 'Bienvenue sur SEN Workshop. Créez des faces visuelles complètes pour SEN Light Novels (Chambre de Lecture et Codex Vivant).',
        codex_secret_title: 'Le Pouvoir du Mode Dual',
        codex_secret_desc1: 'Le mode standard génère des itérations alternatives basées sur un seul profil.',
        codex_secret_desc2: 'Activez le Mode Dual pour générer deux flux en parallèle :',
        codex_universe_a: 'Univers A',
        codex_universe_a_desc: 'Créé avec le profil A',
        codex_universe_b: 'Univers B',
        codex_universe_b_desc: 'Créé avec le profil B',
        codex_fusion_title: 'Chambre de Fusion Activée',
        codex_fusion_desc: 'Fusionnez les meilleures caractéristiques des deux univers en un chef-d\'œuvre unique.',
        codex_presets_title: 'Cibles de Face Visuelle',
        codex_presets_desc: 'SEN Workshop se concentre sur deux cibles complètes :',
        codex_preset_free: 'Forme Libre',
        codex_preset_free_desc: 'Génération libre.',
        codex_preset_icon: 'Chambre de Lecture',
        codex_preset_icon_desc: 'Thème visuel coordonné pour la lecture immersive, la typographie, l\'atmosphère et la narration audio.',
        codex_preset_player: 'Codex Vivant',
        codex_preset_player_desc: 'Thème visuel coordonné pour l\'encyclopédie du lore, les personnages, artefacts, créatures et factions.',
        codex_preset_plugin: 'Codex Vivant',
        codex_preset_plugin_desc: 'Encyclopédie du lore interactive.',
        codex_preset_deco: 'Chambre de Lecture',
        codex_preset_deco_desc: 'Expérience de lecture et typographie.',
        codex_footer: 'Créé pour la Bibliothèque Céleste de SEN Light Novels.'
    },
    pt: {
        app_title: 'SEN Workshop',
        app_sub: 'Visual faces para SEN Light Novels (Câmara de Leitura & Codex Vivo)',
        created_by: 'Criado para SEN Light Novels',
        dual_mode_on: 'Modo Dual: ATIVO',
        dual_mode_off: 'Modo Dual: DESATIVADO',
        settings_title: 'Configurações',
        library_title: 'Biblioteca',
        how_to_use: 'Como Usar',
        fuse_master: 'Fundir Face Visual Mestra',
        exit_error: 'Recomeçar / Sair',
        gen_failed: 'Falha na Geração',
        pres_select: 'Selecione uma face...',
        btn_send: 'Gerar Face',
        vibe_dna: 'Customizador de DNA de Estilo',
        saved_to_lib: 'Face visual salva na Biblioteca!',
        no_components: 'Nenhuma face visual salva ainda.',
        save_btn: 'Salvar Face',
        revert_btn: 'Reverter',
        export_btn: 'Exportar Face',
        source_code: 'Código Fonte',
        variations_title: 'Variações',
        choose_preset: 'Escolher Alvo da Face',
        loading: 'Gerando Face Visual...',
        error_occured: 'Ocorreu um erro durante a geração.',
        speech_dictate: 'Ditado de voz',
        codex_title: 'O Codex Celestial 📖',
        codex_welcome: 'Bem-vindo ao SEN Workshop. Desenvolva faces visuais completas para o SEN Light Novels (Câmara de Leitura e Codex Vivo).',
        codex_secret_title: 'O Poder do Modo Dual',
        codex_secret_desc1: 'O modo padrão gera iterações com base em um único perfil.',
        codex_secret_desc2: 'Ative o Modo Dual para executar dois fluxos em paralelo:',
        codex_universe_a: 'Universo A',
        codex_universe_a_desc: 'Gerado com o perfil A',
        codex_universe_b: 'Universo B',
        codex_universe_b_desc: 'Gerado com o perfil B',
        codex_fusion_title: 'Câmara de Fusão Ativada',
        codex_fusion_desc: 'Combine as melhores características visuais em uma obra-prima unificada.',
        codex_presets_title: 'Alvos de Face Visual',
        codex_presets_desc: 'SEN Workshop é focado em dois alvos completos:',
        codex_preset_free: 'Forma Livre',
        codex_preset_free_desc: 'Geração livre.',
        codex_preset_icon: 'Câmara de Leitura',
        codex_preset_icon_desc: 'Tema visual coordenado para leitura imersiva, tipografia, atmosfera e controles de narração.',
        codex_preset_player: 'Codex Vivo',
        codex_preset_player_desc: 'Tema visual coordenado para enciclopédia do universo, personagens, artefatos, feras e facções.',
        codex_preset_plugin: 'Codex Vivo',
        codex_preset_plugin_desc: 'Enciclopédia interativa do universo.',
        codex_preset_deco: 'Câmara de Leitura',
        codex_preset_deco_desc: 'Experiência de leitura e sistema de tipografia.',
        codex_footer: 'Criado para a Biblioteca Celestial do SEN Light Novels.'
    }
};

export const getLanguage = (): Language => {
    return (localStorage.getItem('sea_language') as Language) || 'en';
};

export const setLanguage = (lang: Language): void => {
    localStorage.setItem('sea_language', lang);
};

export function useLanguage() {
    const [lang, setLangState] = useState<Language>(getLanguage);

    const changeLanguage = (newLang: Language) => {
        setLanguage(newLang);
        setLangState(newLang);
        window.dispatchEvent(new Event('languagechange'));
    };

    useEffect(() => {
        const handleLangChange = () => {
            setLangState(getLanguage());
        };
        window.addEventListener('languagechange', handleLangChange);
        return () => window.removeEventListener('languagechange', handleLangChange);
    }, []);

    const t = (key: string): string => {
        const dict = LOCALIZATION_DICTS[lang] || LOCALIZATION_DICTS.en;
        return dict[key] || LOCALIZATION_DICTS.en[key] || key;
    };

    return { lang, changeLanguage, t };
}
